NZWalks.Web/Controllers/AuthController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NZWalks.Web.Models;
using NZWalks.Web.Services.IServices;
using System.Security.Claims;
using NZWalks.Web.Models.DTO;

namespace NZWalks.Web.Controllers
{
    public class AuthController : Controller
    {
        private readonly IAuthService _authService;
        public AuthController(IAuthService authService)
        {
            _authService = authService;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequest obj = new();
            return View(obj);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginRequest obj)
        {
            APIResponse respone = await _authService.LoginAsync<APIResponse>(obj);
            if (respone != null && respone.IsSuccess)
            {
                LoginResponse model = JsonConvert.DeserializeObject<LoginResponse>(Convert.ToString(respone.Result));
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(ClaimTypes.Name, model.User.UserName));
                identity.AddClaim(new Claim(ClaimTypes.Role, model.User.Role));
                var principle = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principle);
                HttpContext.Session.SetString(SD.SessionToken, model.Token);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("CustomError", respone.ErrorMessages.FirstOrDefault());
                return View(obj);
            }

        }

        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(RegisterationRequestDTO obj)
        {
            APIResponse result = await _authService.RegisterAsync<APIResponse>(obj);
            if (result != null && result.IsSuccess)
            {
                return RedirectToAction("Login");
            }
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.SetString(SD.SessionToken, "");
            return RedirectToAction("Index", "Home");
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

NZWalks.Web/Controllers/RegionController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NZWalks.Web.Models;
using NZWalks.Web.Models.DTO;
using NZWalks.Web.Services.IServices;

namespace NZWalks.Web.Controllers
{
    public class RegionController : Controller
    {
        private readonly IRegionService _regionService;
        private readonly IMapper _mapper;
        public RegionController(IRegionService regionService, IMapper mapper)
        {
            _regionService = regionService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexRegion()
        {
            List<RegionDTO> list = new();
            var respone = await _regionService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<RegionDTO>>(Convert.ToString(respone.Result));
            }

            return View(list);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateRegion()
        {

            return View();
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateRegion(AddRegionRequest model)
        {
            if (ModelState.IsValid)
            {
                var respone = await _regionService.AddAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (respone != null && respone.IsSuccess)
                {
                    TempData["success"] = "Region created successfully";
                    return RedirectToAction(nameof(IndexRegion));
                }
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateRegion(Guid id)
        {
            var respone = await _regionService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {

                RegionDTO model = JsonConvert.DeserializeObject<RegionDTO>(Convert.ToString(respone.Result));
                return View(_mapper.Map<UpdateRegionRequest>(model));
            }
            return NotFound();

        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateRegion(Guid id, UpdateRegionRequest model)
        {
            if (ModelState.IsValid)
            {
                model.Id = id;
                var respone = await _regionService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (respone != null && respone.IsSuccess)
                {
                    TempData["success"] = "Region updated successfully";
                    return RedirectToAction(nameof(IndexRegion));
                }
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteRegion(Guid id)
        {
            var respone = await _regionService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                RegionDTO model = JsonConvert.DeserializeObject<RegionDTO>(Convert.ToString(respone.Result));
                return View(model);
            }
            return NotFound();
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteRegion(Guid id, RegionDTO model)
        {
            model.Id = id;
            var respone = await _regionService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                TempData["success"] = "Region deleted successfully";
                return RedirectToAction(nameof(IndexRegion));
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }
    }
}

NZWalks.Web/Controllers/WalkController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using NZWalks.Web.Models;
using NZWalks.Web.Models.DTO;
using NZWalks.Web.Services.IServices;

namespace NZWalks.Web.Controllers
{
    public class WalkController : Controller
    {
        private readonly IWalkService _walkService;
        private readonly IRegionService _regionService;
        private readonly IWalkDifficultyService _walkDifficultyService;
        private readonly IMapper _mapper;
        public WalkController(IWalkService walkService, IMapper mapper, IRegionService regionService, IWalkDifficultyService walkDifficultyService)
        {
            _walkService = walkService;
            _mapper = mapper;
            _regionService = regionService;
            _walkDifficultyService = walkDifficultyService;
        }
        public async Task<IActionResult> IndexWalk()
        {
            List<WalkDTO> list = new();
            var respone = await _walkService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<WalkDTO>>(Convert.ToString(respone.Result));
            }
            
            return View(list);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateWalk()
        {
            //them
            AddWalkRequestVM addWalkRequest = new();
            var responeRegion = await _regionService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responeRegion != null && responeRegion.IsSuccess)
            {
                addWalkRequest.RegionList = JsonConvert
                    .DeserializeObject<List<RegionDTO>>(Convert.ToString(responeRegion.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            var responeWalkDifficulty = await _walkDifficultyService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responeWalkDifficulty != null && responeWalkDifficulty.IsSuccess)
            {
                addWalkRequest.WalkDifficultyList = JsonConvert
                    .DeserializeObject<List<WalkDifficultyDTO>>(Convert.ToString(responeWalkDifficulty.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Code,
                        Value = i.Id.ToString()
                    });
            }
            //het them
            return View(addWalkRequest);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateWalk(AddWalkRequestVM model)
        {
            if (ModelState.IsValid)
            {
                var respone = await _walkService.AddAsync<APIResponse>(model.Walk, HttpContext.Session.GetString(SD.SessionToken));
                if (respone != null && respone.IsSuccess)
                {
                    TempData["success"] = "Walk created successfully";
                    return RedirectToAction(nameof(IndexWalk));
                }
            }

            //them
            var resRegion = await _regionService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (resRegion != null && resRegion.IsSuccess)
            {
                model.RegionList = JsonConvert
                    .DeserializeObject<List<RegionDTO>>(Convert.ToString(resRegion.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }

            var resWalkDifficulty = await _walkDifficultyService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (resWalkDifficulty != null && resWalkDifficulty.IsSuccess)
            {
                model.WalkDifficultyList = JsonConvert
                    .DeserializeObject<List<WalkDifficultyDTO>>(Convert.ToString(resWalkDifficulty.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Code,
                        Value = i.Id.ToString()
                    });
            }
            //het them

            //TempData["error"] = "Error encountered";
            return View(model);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateWalk(Guid id)
        {
            //them
            UpdateWalkRequestVM updateWalkRequestVM = new();
            var responeRegion = await _regionService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responeRegion != null && responeRegion.IsSuccess)
            {
                updateWalkRequestVM.RegionList = JsonConvert
                    .DeserializeObject<List<RegionDTO>>(Convert.ToString(responeRegion.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Name,
                        Value = i.Id.ToString()
                    });
            }
            var responeWalkDifficulty = await _walkDifficultyService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (responeWalkDifficulty != null && responeWalkDifficulty.IsSuccess)
            {
                updateWalkRequestVM.WalkDifficultyList = JsonConvert
                    .DeserializeObject<List<WalkDifficultyDTO>>(Convert.ToString(responeWalkDifficulty.Result))
                    .Select(i => new SelectListItem
                    {
                        Text = i.Code,
                        Value = i.Id.ToString()
                    });
            }
            //het them
            var respone = await _walkService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {

                WalkDTO model = JsonConvert.DeserializeObject<WalkDTO>(Convert.ToString(respone.Result));
                updateWalkRequestVM.Walk = _mapper.Map<UpdateWalkRequest>(model);
                return View(updateWalkRequestVM);
            }
            return NotFound();

        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateWalk(Guid id, UpdateWalkRequestVM model)
        {
            if (ModelState.IsValid)
            {
                model.Walk.Id = id;
                //them
                //UpdateWalkRequestVM updateWalkRequestVM = new();
                var responeRegion = await _regionService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
                if (responeRegion != null && responeRegion.IsSuccess)
                {
                    model.RegionList = JsonConvert
                        .DeserializeObject<List<RegionDTO>>(Convert.ToString(responeRegion.Result))
                        .Select(i => new SelectListItem
                        {
                            Text = i.Name,
                            Value = i.Id.ToString()
                        });
                }
                var responeWalkDifficulty = await _walkDifficultyService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
                if (responeWalkDifficulty != null && responeWalkDifficulty.IsSuccess)
                {
                    model.WalkDifficultyList = JsonConvert
                        .DeserializeObject<List<WalkDifficultyDTO>>(Convert.ToString(responeWalkDifficulty.Result))
                        .Select(i => new SelectListItem
                        {
                            Text = i.Code,
                            Value = i.Id.ToString()
                        });
                }
                //het them

                var respone = await _walkService.UpdateAsync<APIResponse>(model.Walk, HttpContext.Session.GetString(SD.SessionToken));
                if (respone != null && respone.IsSuccess)
                {
                    TempData["success"] = "Walk updated successfully";
                    return RedirectToAction(nameof(IndexWalk));
                }
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteWalk(Guid id)
        {
            var respone = await _walkService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                WalkDTO model = JsonConvert.DeserializeObject<WalkDTO>(Convert.ToString(respone.Result));
                return View(model);
            }
            return NotFound();
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteWalk(Guid id, RegionDTO model)
        {
            model.Id = id;
            var respone = await _walkService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                TempData["success"] = "Walk deleted successfully";
                return RedirectToAction(nameof(IndexWalk));
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }
    }
}

NZWalks.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor httpAcc
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NZWalks.Web</title>
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NZWalks.Web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
</head>
<body>
    <partial name="_Notification" />
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-dark  box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">NZWalks.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Region" asp-action="IndexRegion">Region</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Walk" asp-action="IndexWalk">Walk</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="WalkDifficulty" asp-action="IndexWalkDifficulty">WalkDifficulty</a>
                        </li>
                        @if (httpAcc.HttpContext.Session.GetString(SD.SessionToken) != null
                        && httpAcc.HttpContext.Session.GetString(SD.SessionToken).ToString().Length > 0)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Logout">Logout</a>
                            </li>
                        }

                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Auth" asp-action="Register">Register</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class=" footer text-muted">
        <div class="container">
            &copy; 2022 - NZWalks.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NZWalks.Web/Views/Shared/_Notification.cshtml
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

@if (TempData["success"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'success',
            title: '@TempData["success"]',
            showConfirmButton: false,
            timer: 1500,
            timerProgressBar: true
        })
    </script>
}

@if (TempData["error"] != null)
{
    <script type="text/javascript">
        Swal.fire({
            position: 'top-end',
            icon: 'error',
            title: '@TempData["error"]',
            showConfirmButton: false,
            timer: 1500,
            timerProgressBar: true
        })
    </script>
}