NZWalks.Web/Controllers/WalkDifficultyController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NZWalks.Web.Models;
using NZWalks.Web.Models.DTO;
using NZWalks.Web.Services;
using NZWalks.Web.Services.IServices;

namespace NZWalks.Web.Controllers
{
    public class WalkDifficultyController : Controller
    {
        private readonly IWalkDifficultyService _walkDifficultyService;
        private readonly IMapper _mapper;
        public WalkDifficultyController(IWalkDifficultyService walkDifficultyService, IMapper mapper)
        {
            _walkDifficultyService = walkDifficultyService;
            _mapper = mapper;
        }
        public async Task<IActionResult> IndexWalkDifficulty()
        {
            List<WalkDifficultyDTO> list = new();
            var respone = await _walkDifficultyService.GetAllAsync<APIResponse>(HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                list = JsonConvert.DeserializeObject<List<WalkDifficultyDTO>>(Convert.ToString(respone.Result));
            }

            return View(list);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> CreateWalkDifficulty()
        {

            return View();
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateWalkDifficulty(AddWalkDifficultyRequest model)
        {
            if (ModelState.IsValid)
            {
                var respone = await _walkDifficultyService.AddAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (respone != null && respone.IsSuccess)
                {
                    TempData["success"] = "WalkDifficulty created successfully";
                    return RedirectToAction(nameof(IndexWalkDifficulty));
                }
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> UpdateWalkDifficulty(Guid id)
        {
            var respone = await _walkDifficultyService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {

                WalkDifficultyDTO model = JsonConvert.DeserializeObject<WalkDifficultyDTO>(Convert.ToString(respone.Result));
                return View(_mapper.Map<UpdateWalkDifficultyRequest>(model));

            }
            return NotFound();

        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateWalkDifficulty(Guid id, UpdateWalkDifficultyRequest model)
        {
            if (ModelState.IsValid)
            {
                model.Id = id;
                
                var respone = await _walkDifficultyService.UpdateAsync<APIResponse>(model, HttpContext.Session.GetString(SD.SessionToken));
                if (respone != null && respone.IsSuccess)
                {
                    TempData["success"] = "WalkDifficulty updated successfully";
                    return RedirectToAction(nameof(IndexWalkDifficulty));
                }
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }

        //[Authorize(Roles = "admin")]
        public async Task<IActionResult> DeleteWalkDifficulty(Guid id)
        {
            var respone = await _walkDifficultyService.GetAsync<APIResponse>(id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                WalkDifficultyDTO model = JsonConvert.DeserializeObject<WalkDifficultyDTO>(Convert.ToString(respone.Result));
                return View(model);
            }
            return NotFound();
        }

        //[Authorize(Roles = "admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteWalkDifficulty(Guid id, WalkDifficultyDTO model)
        {
            model.Id = id;
            var respone = await _walkDifficultyService.DeleteAsync<APIResponse>(model.Id, HttpContext.Session.GetString(SD.SessionToken));
            if (respone != null && respone.IsSuccess)
            {
                TempData["success"] = "WalkDifficulty deleted successfully";
                return RedirectToAction(nameof(IndexWalkDifficulty));
            }
            TempData["error"] = "Error encountered";
            return View(model);
        }
    }
}

NZWalks.Web/Views/WalkDifficulty/CreateWalkDifficulty.cshtml
@model NZWalks.Web.Models.DTO.AddWalkDifficultyRequest

<form asp-action="CreateWalkDifficulty">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Create WalkDifficulty</h1>
        <hr />

        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Code" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            

            <div class="col-5">
                <a asp-action="IndexWalkDifficulty" asp-controller="WalkDifficulty" class="btn btn-primary form-control">Back to list</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Create" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

NZWalks.Web/Views/WalkDifficulty/DeleteWalkDifficulty.cshtml
@model NZWalks.Web.Models.DTO.WalkDifficultyDTO

<form asp-action="DeleteWalkDifficulty">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Delete WalkDifficulty</h1>
        <hr />
        @*<input hidden asp-for="Id" />*@
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Code" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Code" disabled class="form-control" />
            </div>


            <div class="col-5">
                <a asp-action="IndexWalkDifficulty" asp-controller="WalkDifficulty" class="btn btn-primary form-control">Back to list</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Delete" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

NZWalks.Web/Views/WalkDifficulty/IndexWalkDifficulty.cshtml
@model IEnumerable<NZWalks.Web.Models.DTO.WalkDifficultyDTO>
<br />
<div class="container p-4 border">
    <div class="row pb-2">
        <div class="col">
            <h1 class="text-primary">WalkDifficulty List</h1>
        </div>
        <div class="col text-end pt-1">
            <a asp-controller="WalkDifficulty" asp-action="CreateWalkDifficulty" class="btn btn-outline-primary"><i class="bi bi-plus-square-fill"></i> Create New WalkDifficulty</a>
        </div>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Code</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.Code</td>
                    
                    <td>
                        <a asp-controller="WalkDifficulty" asp-action="UpdateWalkDifficulty" asp-route-id="@item.Id" class="btn btn-outline-success"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="WalkDifficulty" asp-action="DeleteWalkDifficulty" asp-route-id="@item.Id" class="btn btn-outline-danger"><i class="bi bi-trash-fill"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

NZWalks.Web/Views/WalkDifficulty/UpdateWalkDifficulty.cshtml
@model NZWalks.Web.Models.DTO.UpdateWalkDifficultyRequest

<form asp-action="UpdateWalkDifficulty">
    <br />
    <div class="container border p-3">
        <h1 class="text-primary">Update WalkDifficulty</h1>
        <hr />
        <input hidden asp-for="Id"/>
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="col-2">
                <label asp-for="Code" class="control-label pt-2" style="font-size:20px"></label>
            </div>
            <div class="col-10 pb-3">
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>

            

            <div class="col-5">
                <a asp-action="IndexWalkDifficulty" asp-controller="WalkDifficulty" class="btn btn-primary form-control">Back to list</a>
            </div>
            <div class="col-5">
                <input type="submit" value="Update" class="btn btn-success form-control" />
            </div>
        </div>
    </div>
</form>


@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}